name: lifehq
description: Design your life.

publish_to: 'none'

version: 0.6.2+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Desktop
  desktop_window: ^0.4.0
  sqflite_common_ffi: ^2.1.0

  # DB
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  path_provider: ^2.0.6

  # utils
  url_launcher: ^6.0.12
  intl: ^0.17.0
  flutter_local_notifications: ^9.0.0

  # UI
  awesome_emojis:
    git:
      url: https://github.com/daviresio/awesome_emojis.git
      ref: master
  flutter_quill: ^2.0.13
  fluttertoast: ^8.0.8
  cached_network_image: ^3.1.0
  flutter_neat_and_clean_calendar: ^0.2.3+11

  # location
  flutter_map: ^0.14.0
  osm_nominatim: ^2.0.1
  gps:
    git:
      url: https://github.com/bishtmanish739/flutter_gps.git
      ref: master
  latlong2: ^0.8.1


  # Rss
  opmlparser: ^1.0.0
  flutter_html: ^2.1.5
  html_main_element: ^2.1.0
  webfeed: ^0.7.0
  feed_finder: ^1.0.9

  # Security & Privacy
  flutter_screen_lock: ^4.0.4+2
  flutter_secure_storage: ^4.2.1
  local_auth: ^1.1.8

  # Crashlytics & performance
  sentry_flutter: ^6.1.0

dependency_overrides:
  flutter_colorpicker: ^0.6.0

dev_dependencies:
  sqflite_common_ffi: ^2.1.0
  sentry_dart_plugin: ^1.0.0-beta.1
  msix: ^2.6.2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.3.1

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "fastlane/metadata/android/en-US/images/icon.png"

flutter:
  assets:
    - assets/loading.gif
  fonts:
  - family: CustomIcons
    fonts:
      - asset: assets/fonts/CustomIcons.ttf
  uses-material-design: true

msix_config:
  display_name: LifeHQ
  publisher_display_name: Abhinav Marwaha
  identity_name: com.abhinavmarwaha.lifehq
  msix_version: 1.0.0.0
  # store: true
  # logo_path: windows\runner\resources\app_icon.ico
  capabilities: 'internetClient'
  assets_directory_path: assets\windows
