name: lifehq
description: Design your life.

publish_to: 'none'

version: 0.5.3+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # DB
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.8
  provider: ^6.0.1

  # utils
  url_launcher: ^6.0.12
  intl: ^0.17.0
  flutter_local_notifications: ^9.0.0

  # UI
  # emojis: ^0.9.3 # non-null safe
  awesome_emojis:
    git:
      url: https://github.com/daviresio/awesome_emojis.git
      ref: master
  flutter_quill: ^2.0.13
  # flutter_html: ^2.1.5
  fluttertoast: ^8.0.8

  # location
  flutter_map: ^0.14.0
  osm_nominatim: ^2.0.1
  # gps: ^0.1.1 # non-null safe
  gps:
    git:
      url: https://github.com/bishtmanish739/flutter_gps.git
      ref: master
  latlong2: ^0.8.1
  cached_network_image: ^3.1.0

dependency_overrides:
  #  flutter_colorpicker: ^0.4.0
  flutter_colorpicker: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.3.1

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "fastlane/metadata/android/en-US/images/icon.png"

flutter:
  assets:
    - assets/loading.gif
  fonts:
  - family: CustomIcons
    fonts:
      - asset: assets/fonts/CustomIcons.ttf
  uses-material-design: true