name: lifehq
version: 0.6.0
summary: Design your Life
description: Design your life journaling, routine and goals.

confinement: strict
base: core18

parts:
  lifehq:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart 
    build-packages:
    - libsecret-1-dev
    - libjsoncpp-dev
    - libsqlite3-0 
    - libsqlite3-dev
    stage-packages:
    - libsecret-1-dev

apps:
  lifehq:
    command: LifeHQ
    extensions: [flutter-stable]
