name: lifehq
version: 0.6.0
summary: Design your Life
description: Design your life journaling, routine and goals.

confinement: strict
base: core18
grade: stable

slots:
  dbus-lifehq:
    interface: dbus
    bus: session
    name: com.abhinavmarwaha.lifehq
    
apps:
  lifehq:
    command: lifehq
    extensions: [flutter-master]
    plugs:
    - network
    slots:
      - dbus-lifehq
parts:
  lifehq:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart 
    build-packages:
    - libsecret-1-dev
    - libjsoncpp-dev
    - libsqlite3-0 
    - libsqlite3-dev
    stage-packages:
    - libsecret-1-dev
